[package]
name = "surrealdb_migrations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "surrealdb_migrations"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0.79"
thiserror = "1.0.56"
surrealdb = "1.1.1"
serde = "1.0.195"
serde_json = "1.0.111"

[dev-dependencies]
tokio = "1.35.1"